### ISSUE TITLE
mean of ELEV_STD and SLOPE_STD in function_UpstreamGeoData.R

### ISSUE THREAD

**Issue by dgustafsson** [rcapell/RHYPE#28]
Great that you added the function_UpstreamGeoData.R!!

Would it be possible to correct the calculation of upstream ELEV_MEAN and ELEV_STD and SLOPE_MEAN and SLOPE_STD using this function for weighted mean and standard deviation (matlab code):

function [mu,sigma] = statofstat(mus,sigmas,weights)
% calulate weighted mean and standard deviation of non-overlapping
% populations
%
% the weights are commonly the number of samples in each population
%
% the weights could be subbasin areas, over wich the mus and sigmas were originally calculated
%
% David Gustafsson, SMHI, 2012-10-15

%mean value
if ~isempty(mus)
    [nPop,nX] = size(mus);
    mu = zeros(1,nX);
    if isempty(weights)
        weights = ones(nPop,1);
    end
    for i=1:nX
        mu(i) = sum(mus(:,i) .* weights) / sum(weights);
    end
else
    mu=[];
end

% standard deviation
if ~isempty(sigmas)
    if isempty(mus)
        disp('ERROR: weigted SIGMA cannot be calculated without MU!')
        sigma = -1;
        return;
    end
    [nPops,nXs] = size(mus);
    if nPops ~= nPop | nXs ~=nX
        disp('ERROR: dimension of SIGMA must be equal to dimension of MU!')
        sigma = -1;
        return;
    end
    sigma = zeros(1,nX);
    if isempty(weights)
        weights = ones(nPop,1);
    end
    for i=1:nX
        sigma(i) = (sum(weights .* (sigmas(:,i).^2 + mus(:,i).^2)) ./ sum(weights) - mu(i).^2 ).^0.5;
    end
else
    sigma=[];
end

**Comment by rcapell** [comment]
Thanks for the mean sd function, i will update UpstreamGeoData. It is only half-done anyway but I will work on it asap..

**Comment by rcapell** [comment]
hint how to do the mean sd calcs elegantly in R:
http://stackoverflow.com/questions/9222056/existing-function-to-combine-standard-deviations-in-r

**Comment by rcapell** [comment]
working version of the function in latest master. @dgustafsson ready for testing :)

closing this ticket for now.
