### ISSUE TITLE
Installation instructions when updating from previous version

### ISSUE THREAD

**Issue by jcmand** [rcapell/RHYPE#32]
The installation instructions on the wiki are good. But I lack a short note about how to update RHYPE from a previous version. Is it necessary to uninstall the previous RHYPE version before install.packages() or is that handled automatically? A short line would help future updaters as well I think.

**Comment by rcapell** [comment]
yes, good question. I don't think you would have to do anything different than with a fresh install, but maybe it is safer to remove first. I couldn't find a definite answer.
I added some lines in the wiki.
