### ISSUE TITLE
Bug? in ReadLakeData

### ISSUE THREAD

**Issue by julzab** [rcapell/RHYPE#40]
Hallo,

using the function _ReadLakeData_ results in the error 

> Error in read.table(file = filename, header = T, na.strings = "-9999",  :   more columns than column names" .

Example: `ReadLakeData("Lakedata.txt")`

However, using the following piece of code it works fine:

`read.table("Lakedata.txt", header = TRUE, sep="\t")`

Thanks a lot for your help,

regards

Julia

**Comment by rcapell** [comment]
Thanks! 
Updated in latest commit. I will release a new version soon.
