### ISSUE TITLE
PlotAnnualRegime from AnnualRegime with incl.leap = T 

### ISSUE THREAD

**Issue by julzab** [rcapell/RHYPE#42]
Hi René 

I used the following piece of code:
``PlotAnnualRegime(x = AnnualRegime(x = cout, ts.in = "day", ts.out = "day", start.mon = 10, incl.leap = T), type="minmax",add.legend = F,col = c("red","blue"), lty = 1, lwd = 2,ylab ="m3/s")``

Unfortunately, no data are plotted for the 29th of February (should be the daily mean of a 30 year period)

Thanks for your help,

Julia

**Comment by julzab** [comment]
OK, got it! It is necessary to set na.rm=T ..... when using incl.leap = T

**Comment by julzab** [comment]
Sorry for the confusion, there seems to be a bug anyway. Writing:
``PlotAnnualRegime(x = AnnualRegime(x = cout, ts.in = "day", ts.out = "day", start.mon = 10, incl.leap = T, na.rm=T), type="p25p75",add.legend = F,col = c("red","blue"), lty = 1, lwd = 2,ylab ="m3/s")
legend("topright", c("a","b"), col = c("red","blue"), lty = c(1,1), bty = "n", lwd = 2, cex = 1.5)``
results in a messed up plot (p25 and p75 wrong, value of 29th of February missing)

/Julia

**Comment by julzab** [comment]
An example of the plot

![example](https://cloud.githubusercontent.com/assets/15359437/14526923/dc57aeb0-0246-11e6-848c-bc4c2a00057c.png)

**Comment by rcapell** [comment]
I think this was a bug in AnnualRegime(), the old implementation could result in an "NA" reference date.
Fixed in master. Can you test with the latest RHYPE code (get it using devtools method)? If it works, please close this issue. Thanks!

**Comment by rcapell** [comment]
Closing for now, please re-open if solution does not work for you!
