### ISSUE TITLE
Improve performance of e.g. ReadTimeOutput()

### ISSUE THREAD

**Issue by wstolte** [rcapell/RHYPE#43]
Benchmark file read functions for EHYPE results
-----------------------------------------------

Function ReadTimeOutput() uses a read.table() function to read the sometimes very large text output files (1G in case of EHYPE). This takes \> 10 minutes on an i5 laptop. This can be improved by using an other read function. I have tested two functions readr::read\_tsv() and data.table::fread() The benchmark is below only for reading the files.

### Base function read.table()

``` r
system.time(cctn1 <- read.table(file.path(hypedir, "timeCCTN.txt"), 
                                header = T, na.strings = "-9999", skip = 1))
```

    ##    user  system elapsed 
    ##  640.19    5.71  657.06

``` r
class(cctn1)
```

    ## [1] "data.frame"

``` r
str(cctn1[1])
```

    ## 'data.frame':    4018 obs. of  1 variable:
    ##  $ DATE: Factor w/ 4018 levels "2003-01-01","2003-01-02",..: 1 2 3 4 5 6 7 8 9 10 ...

### read\_tsv function from the'readr' package

``` r
require(readr)
```

    ## Loading required package: readr

    ## Warning: package 'readr' was built under R version 3.2.3

``` r
system.time(cctn2 <- read_tsv(file.path(hypedir, "timeCCTN.txt"), 
                              col_names = T, na = "-9999", skip = 1))
```

    ##    user  system elapsed 
    ##  178.54    4.66  215.36

``` r
class(cctn1)
```

    ## [1] "data.frame"

``` r
str(cctn2[1])
```

    ## Classes 'tbl_df', 'tbl' and 'data.frame':    4018 obs. of  1 variable:
    ##  $ DATE: Date, format: "2003-01-01" "2003-01-02" ...

### fread function from the 'data.table' package

``` r
require(data.table)
```

    ## Loading required package: data.table

``` r
system.time(cctn3 <- fread(file.path(hypedir, "timeCCTN.txt"), 
                           na.strings = "-9999", skip = 1))
```

    ## 
    Read 0.0% of 4019 rows
    Read 4019 rows and 35409 (of 35409) columns from 1.254 GB file in 00:02:05

    ##    user  system elapsed 
    ##  110.31    0.92  126.03

``` r
class(cctn1)
```

    ## [1] "data.frame"

``` r
str(cctn3[[1]])
```

    ##  chr [1:4019] "DATE" "2003-01-01" "2003-01-02" "2003-01-03" ...

So, both read\_tsv and fread are much faster than the standard function. Running the whole ReadTimeOutput() function, the difference is less, but still a factor of 2. The performance could perhaps further be improved by using the read\_tsv function, because it converts the Date column to Date format while reading.

**Comment by rcapell** [comment]
Great, thanks for testing, I will look into this and consider changing the
read function (also i would like to keep package dependencies to a
minimum).
Note for myself: compare Willem's results with "tuned" read.table call
performance, ie with argument colClasses to define column data types.

**Comment by rcapell** [comment]
I chose fread(), the function from package data.table. Implemented for ReadTimeOutput(). Needs testing, and then transfer to other large-file import functions.

**Comment by rcapell** [comment]
Note: 
ReadTimeOutput() and the TimeOutput part of ReadWsOutput() should be able to use fread()'s "select" argument

**Comment by rcapell** [comment]
ReadTimeOutput(), ReadMapOutput(), ReadWsOutput() updated.

**Comment by rcapell** [comment]
ReadXobs() and  ReadPTQObs() updated, no option to import as data.table for now. Can be added later when/if someone requests it.
ReadGeoData() updated as well.
Closing this issue for now, as all common large-file imports are covered. Can be re-opened if something is missing or wrong.
